import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LayoutGroup, motion } from "framer-motion";
// @ts-ignore - CSS side-effect import lacks type declarations
import "./globals.css";
// @ts-ignore - CSS side-effect import lacks type declarations

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tirthadeep Kapat",
  description: "Generated by Tirtha",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        
      </body>
    </html>
  );
}
